theme: jekyll-theme-minimal
#permalink: /:title
baseurl: ""
title: Welcome to Clouditer
description: Lessons learnt on my Cloud Journey
locale: en_US
show_downloads: false
logo: images/logo.png

owner:
  name: Bas de Zeeuw
  avatar: images/bas.jpg
  bio: "Cloud Systems Consultant at Sentia"
  linkedin: basdezeeuw89
  github: bdzeeuw
  google:
    analytics: UA-166360559-1
