theme: jekyll-theme-tactile
title: Welcome to Clouditer
description: Lessons learnt on my Cloud Journey
locale: en_US
#logo: # filename of a logo image that has been placed into your images directory

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Bas de Zeeuw
  #avatar: bio-photo.jpg
  #bio: "This is a sample Jekyll academic website."
  #email: laderast@ohsu.edu
  # Do not include the @ symbol in your Twitter username
  #twitter: laderast
  linkedin: basdezeeuw89
  github: bdzeeuw
#  google:
#    plus: #username
#    analytics:
#    verify:
#    scholar: #id
