theme: jekyll-theme-minimal
title: Welcome to Clouditer
description: Lessons learnt on my Cloud Journey
locale: en_US
logo: logo.png

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Bas de Zeeuw
  avatar: bas.jpg
  bio: "Cloud Systems Consultant at Sentia"
  #email: laderast@ohsu.edu
  # Do not include the @ symbol in your Twitter username
  #twitter: laderast
  linkedin: basdezeeuw89
  github: bdzeeuw
#  google:
#    plus: #username
#    analytics:
#    verify:
#    scholar: #id
